import PDFDocument from 'pdfkit';

export interface InvoiceData {
  number: string;
  date: string;
  dueDate: string;
  seller: {
    name: string;
    inn: string;
    kpp?: string;
    address: string;
    phone?: string;
  };
  buyer: {
    name: string;
    inn: string;
    kpp?: string;
    address: string;
  };
  items: Array<{
    name: string;
    quantity: number;
    price: number;
    total: number;
    vat: number;
  }>;
  subtotal: number;
  vatRate: number;
  vatAmount: number;
  total: number;
  paymentTerms: string;
}

export async function generateInvoice(data: InvoiceData): Promise<Uint8Array> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Header
      doc.fontSize(18).font('Helvetica-Bold').text('СЧЁТ НА ОПЛАТУ', { align: 'center' });
      doc.moveDown();
      doc.fontSize(12).font('Helvetica').text(`№ ${data.number} от ${data.date}`, { align: 'right' });
      doc.moveDown(2);

      // Seller
      doc.fontSize(10).font('Helvetica-Bold').text('Продавец:', { underline: true });
      doc.font('Helvetica').text(data.seller.name);
      doc.text(`ИНН ${data.seller.inn}${data.seller.kpp ? ' / КПП ' + data.seller.kpp : ''}`);
      doc.text(data.seller.address);
      if (data.seller.phone) doc.text(data.seller.phone);
      doc.moveDown();

      // Buyer
      doc.font('Helvetica-Bold').text('Покупатель:', { underline: true });
      doc.font('Helvetica').text(data.buyer.name);
      doc.text(`ИНН ${data.buyer.inn}${data.buyer.kpp ? ' / КПП ' + data.buyer.kpp : ''}`);
      doc.text(data.buyer.address);
      doc.moveDown(2);

      // Items table header
      doc.font('Helvetica-Bold');
      const tableTop = doc.y;
      doc.text('Наименование', 50, tableTop, { width: 250 });
      doc.text('Кол-во', 300, tableTop, { width: 60, align: 'center' });
      doc.text('Цена', 360, tableTop, { width: 80, align: 'right' });
      doc.text('Сумма', 440, tableTop, { width: 80, align: 'right' });
      doc.moveDown();

      // Line
      doc.moveTo(50, doc.y).lineTo(520, doc.y).stroke();
      doc.moveDown();

      // Items
      doc.font('Helvetica');
      for (const item of data.items) {
        const rowY = doc.y;
        doc.text(item.name, 50, rowY, { width: 250 });
        doc.text(item.quantity.toString(), 300, rowY, { width: 60, align: 'center' });
        doc.text(`${item.price} ₽`, 360, rowY, { width: 80, align: 'right' });
        doc.text(`${item.total} ₽`, 440, rowY, { width: 80, align: 'right' });
        doc.moveDown();
      }

      doc.moveDown();
      doc.moveTo(50, doc.y).lineTo(520, doc.y).stroke();
      doc.moveDown();

      // Totals
      doc.font('Helvetica');
      const totalY = doc.y;
      doc.text('Итого:', 360, totalY, { width: 80, align: 'right' });
      doc.text(`${data.subtotal} ₽`, 440, totalY, { width: 80, align: 'right' });
      doc.moveDown();

      doc.text(`НДС ${data.vatRate}%:`, 360, doc.y, { width: 80, align: 'right' });
      doc.text(`${data.vatAmount} ₽`, 440, doc.y, { width: 80, align: 'right' });
      doc.moveDown();

      doc.font('Helvetica-Bold');
      doc.text('К ОПЛАТЕ:', 360, doc.y, { width: 80, align: 'right' });
      doc.fontSize(12).text(`${data.total} ₽`, 440, doc.y, { width: 80, align: 'right' });
      doc.moveDown(2);

      // Payment terms
      doc.fontSize(10).font('Helvetica');
      doc.text(`Срок оплаты: ${data.paymentTerms}`, 50);
      doc.text(`Оплатить до: ${data.dueDate}`, 50);
      doc.moveDown(2);

      // Footer
      doc.fontSize(8).text('Generated by Logistics Optimizer', { align: 'center' });

      doc.end();
    } catch (e) {
      reject(e);
    }
  });
}

export interface TTNData {
  number: string;
  date: string;
  sender: any;
  receiver: any;
  carrier: any;
  driver: any;
  vehicle: any;
  cargo: any[];
  totalWeight: number;
  totalQuantity: number;
  loadingAddress: string;
  unloadingAddress: string;
}

export async function generateTTN(data: TTNData): Promise<Uint8Array> {
  return generateInvoice({
    number: data.number,
    date: data.date,
    dueDate: data.date,
    seller: data.sender,
    buyer: data.receiver,
    items: data.cargo.map(c => ({
      name: c.name,
      quantity: c.quantity,
      price: 0,
      total: 0,
      vat: 0,
    })),
    subtotal: 0,
    vatRate: 0,
    vatAmount: 0,
    total: 0,
    paymentTerms: '',
  });
}